### ISSUE TITLE
UE5 support

### ISSUE THREAD

**Issue by LuisBurdallo** [rnixik/spider-navigation-plugin#3]
Not entirely sure if you are the creator of this plugin but it seems there is nothing like this anywhere and I was wondering if this could be updated to make it work in UE5. I haven't tried to use it at all because I guess it is too old to work out of the box. Any idea if this is feasible or if any other wall navigation system?

**Comment by LuisBurdallo** [comment]
I am trying to compile but I get these errors:
```
1>[7/11] Compile Module.SpiderNavigation.cpp
1>D:\Unreal Projects\PluginsTest\Plugins\SpiderNavigation\Source\SpiderNavigation\Private\SpiderNavGridBuilder.cpp(159): error C2039: 'bTraceAsyncScene': is not a member of 'FCollisionQueryParams'
1>C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Engine\Classes\GameFramework\PlayerController.h(46): note: see declaration of 'FCollisionQueryParams'
1>D:\Unreal Projects\PluginsTest\Plugins\SpiderNavigation\Source\SpiderNavigation\Private\SpiderNavGridBuilder.cpp(234): error C2039: 'bTraceAsyncScene': is not a member of 'FCollisionQueryParams'
1>C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Engine\Classes\GameFramework\PlayerController.h(46): note: see declaration of 'FCollisionQueryParams'
1>D:\Unreal Projects\PluginsTest\Plugins\SpiderNavigation\Source\SpiderNavigation\Private\SpiderNavGridBuilder.cpp(440): error C2039: 'bTraceAsyncScene': is not a member of 'FCollisionQueryParams'
1>C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Engine\Classes\GameFramework\PlayerController.h(46): note: see declaration of 'FCollisionQueryParams'
1>D:\Unreal Projects\PluginsTest\Plugins\SpiderNavigation\Source\SpiderNavigation\Private\SpiderNavGridBuilder.cpp(480): error C2039: 'bTraceAsyncScene': is not a member of 'FCollisionQueryParams'
1>C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Engine\Classes\GameFramework\PlayerController.h(46): note: see declaration of 'FCollisionQueryParams'
1>[8/11] Link UnrealEditor-SpiderNavigation.dll cancelled
1>[9/11] Link UnrealEditor-SpiderNavigation.lib cancelled
1>[10/11] Link UnrealEditor-PluginsTest.dll
```

**Comment by Joubert123** [comment]
Simply comment out the lines where those properties are being set. They were removed in 4.22

I got it working in UE5.1

https://forums.unrealengine.com/t/c-transition-guide-for-4-22/124408/8

**Comment by ferlix9o** [comment]
Thank you Joubert123 that helped me fixing those errors.

I am trying to compile for 5.4 and now i have this :

------ Building 4 action(s) started ------
[1/4] Compile [x64] Module.SpiderNavigation.cpp
...\spider-navigation-plugin-master_UE5\HostProject\Plugins\SpiderNavigation\Source\SpiderNavigation\Private\SpiderNavGridBuilder.cpp(370): error C2079: 'OverlapResult' uses undefined struct 'FOverlapResult'
...spider-navigation-plugin-master_UE5\HostProject\Plugins\SpiderNavigation\Source\SpiderNavigation\Private\SpiderNavGridBuilder.cpp(370): error C2027: use of undefined type 'FOverlapResult'
...\Runtime\Engine\Classes\Components\PrimitiveComponent.h(52): note: see declaration of 'FOverlapResult'

any idea on how to fix this error ?
Thanks !
